bulan = input("Masukkan bulan (1-12) : ")
if bulan == '1':
    print("Jumlah Hari : 31")
elif bulan == '2':
    print("Jumlah Hari : 28")
elif bulan == '3':
    print("Jumlah Hari : 30")
elif bulan == '4':
    print("Jumlah Hari : 30")
elif bulan == '5':
    print("Jumlah Hari : 31")
elif bulan == '6':
    print("Jumlah Hari : 30")
elif bulan == '7':
    print("Jumlah Hari : 31")
elif bulan == '8':
    print("Jumlah Hari : 31")
elif bulan == '9':
    print("Jumlah Hari : 30")
elif bulan == '10':
    print("Jumlah Hari : 31")
elif bulan == '11':
    print("Jumlah Hari : 30")
elif bulan == '12':
    print("Jumlah Hari : 31")
